# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:year/:month/:day/:title/
relative_permalinks: true

# Setup
title: "Aşkın Gedik"
tagline: "askn@askngdk:~$"
description: "Aşkın'ın Web Günlüğü"
url: http://askingedik.net
baseurl: /
paginate: 13

# About/contact
author:
  name:              Aşkın Gedik
  url:               https://twitter.com/askngdk
  email:             askngdk@gmail.com

# Custom vars
version:             1.0.0

facebook: "askngdk"
linkedin: "askngdk"
twitter: "askngdk"
github_u: 'askn'
instagram: 'askngdk'
googleplus: "101664352366673735839"

disqus_short_name: 'askngdk'
google_analytics_tracking_id: UA-34813647-1
email: "askngdk@gmail.com"
